model_path: huzama/Full-3.2-16L
model_name: Full-3.2-16L
num_layers: 16
dataset_name: boolq
revision: pico-epoch_0
batch_size: 64
max_length: 2048
device: cuda
prune_layers: []
num_layers_to_skip: 1
method: taylor
evaluators:
  - label: piqa 
  - label: hellaswag 
  - label: winogrande 
  - label: openbook_qa 
  - label: boolq 
  - label: arc_easy 
  - label: copa 
  - label: social_iqa 
  - label: boolq_val_mc_5shot
  - label: hellaswag_mc_5shot
  - label: piqa_mc_5shot
  - label: openbookqa_mc_5shot
  - label: winogrande_mc_5shot
  - label: arc_easy_mc_5shot
  - label: csqa_mc_5shot