model_path: meta-llama/Meta-Llama-3-8B
model_name: Meta-Llama-3-8B
num_layers: 32
dataset_name: wikitext
revision: main
batch_size: 8
max_length: 2048
device: cuda
prune_layers: []
method: similarity-based
evaluators:
  - label: piqa 
  - label: hellaswag 
  - label: winogrande 
  - label: openbook_qa 
  - label: boolq 
  - label: arc_easy 
  - label: copa 
  - label: social_iqa 
  - label: boolq_val_mc_5shot
  - label: hellaswag_mc_5shot
  - label: piqa_mc_5shot
  - label: openbookqa_mc_5shot
  - label: winogrande_mc_5shot
  - label: arc_easy_mc_5shot
  - label: csqa_mc_5shot