model_path: huzama/Vanilla-3.2-8L
model_name: Vanilla-3.2-8L
num_layers: 8
dataset_name: pico-lm/pretokenized-dolma
dataset_size: 1280
revision: pico-epoch_0
batch_size: 8
max_length: 2048
device: cuda
# num_layers_to_skip: 3
# method : similarity-based
prune_layer: 6
method : prune-one